export const CarsBrands = {
  TOYOTA: "Toyota",
  FORD: "Ford", 
  CHEVROLET: "Chevrolet",
  VOLKSWAGEN: "Volkswagen",
  RENAULT: "Renault",
  PEUGEOT: "Peugeot",
  FIAT: "Fiat",
  HONDA: "Honda",
  NISSAN: "Nissan",
  HYUNDAI: "Hyundai",
  KIA: "Kia",
  JEEP: "Jeep",
  RAM: "Ram",
  CITROEN: "Citroën",
  MERCEDES_BENZ: "Mercedes-Benz",
  BMW: "BMW",
  AUDI: "Audi",
  PORSCHE: "Porsche",
  FERRARI: "Ferrari",
  LAMBORGHINI: "Lamborghini",
  MASERATI: "Maserati",
  BENTLEY: "Bentley",
  ROLLS_ROYCE: "Rolls-Royce",
  ASTON_MARTIN: "Aston Martin",
  JAGUAR: "Jaguar",
  LAND_ROVER: "Land Rover",
  VOLVO: "Volvo",
  LEXUS: "Lexus",
  INFINITI: "Infiniti",
  ACURA: "Acura",
  CADILLAC: "Cadillac",
  LINCOLN: "Lincoln",
  MAZDA: "Mazda",
  MITSUBISHI: "Mitsubishi",
  SUZUKI: "Suzuki",
  SUBARU: "Subaru",
  ISUZU: "Isuzu",
  SSANGYONG: "SsangYong",
  CHERY: "Chery",
  JAC: "JAC",
  GEELY: "Geely",
  GREAT_WALL: "Great Wall",
  HAVAL: "Haval",
  LIFAN: "Lifan",
  DONGFENG: "Dongfeng",
  FOTON: "Foton",
  JMC: "JMC",
  CHANGAN: "Changan",
  BYD: "BYD",
  MG: "MG",
  ALFA_ROMEO: "Alfa Romeo",
  LANCIA: "Lancia",
  SEAT: "Seat",
  SKODA: "Skoda",
  OPEL: "Opel",
  SAAB: "Saab",
  SATURN: "Saturn",
  PONTIAC: "Pontiac",
  OLDSMOBILE: "Oldsmobile",
  MERCURY: "Mercury",
  PLYMOUTH: "Plymouth",
  DODGE: "Dodge",
  CHRYSLER: "Chrysler",
  HUMMER: "Hummer",
  DAEWOO: "Daewoo",
  DAIHATSU: "Daihatsu",
  IVECO: "Iveco",
  SCANIA: "Scania",
  VOLVO_TRUCKS: "Volvo Trucks",
  MERCEDES_BENZ_TRUCKS: "Mercedes-Benz Trucks",
  MAN: "MAN",
  DAF: "DAF",
  FREIGHTLINER: "Freightliner",
  KENWORTH: "Kenworth",
  PETERBILT: "Peterbilt",
  INTERNATIONAL: "International",
  IKA: "IKA",
  SIAM: "Siam",
  DINARG: "Dinarg",
  AUTOAR: "Autoar",
  RASTROJERO: "Rastrojero",
  DACIA: "Dacia",
  LADA: "Lada",
  TATA: "Tata",
  MAHINDRA: "Mahindra",
  PROTON: "Proton",
  PERODUA: "Perodua",
  MCLAREN: "McLaren",
  KOENIGSEGG: "Koenigsegg",
  BUGATTI: "Bugatti",
  PAGANI: "Pagani",
  TESLA: "Tesla",
  RIVIAN: "Rivian",
  LUCID: "Lucid",
  NIO: "NIO",
  XPENG: "XPeng",
  LI_AUTO: "Li Auto",
  FISKER: "Fisker",
  MINI: "MINI",
  SMART: "Smart",
  MAYBACH: "Maybach",
  DS: "DS",
  GENESIS: "Genesis",
  ALPINE: "Alpine"
} as const;

export type CarBrand = typeof CarsBrands[keyof typeof CarsBrands]