import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSparePartsToCar1775272596631 implements MigrationInterface {
    name = 'AddSparePartsToCar1775272596631'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_car" ("id" varchar PRIMARY KEY NOT NULL, "licensePlate" varchar(7) NOT NULL, "model" varchar NOT NULL, "brand" varchar CHECK( "brand" IN ('Toyota','Ford','Chevrolet','Volkswagen','Renault','Peugeot','Fiat','Honda','Nissan','Hyundai','Kia','Jeep','Ram','Citroën','Mercedes-Benz','BMW','Audi','Porsche','Ferrari','Lamborghini','Maserati','Bentley','Rolls-Royce','Aston Martin','Jaguar','Land Rover','Volvo','Lexus','Infiniti','Acura','Cadillac','Lincoln','Mazda','Mitsubishi','Suzuki','Subaru','Isuzu','SsangYong','Chery','JAC','Geely','Great Wall','Haval','Lifan','Dongfeng','Foton','JMC','Changan','BYD','MG','Alfa Romeo','Lancia','Seat','Skoda','Opel','Saab','Saturn','Pontiac','Oldsmobile','Mercury','Plymouth','Dodge','Chrysler','Hummer','Daewoo','Daihatsu','Iveco','Scania','Volvo Trucks','Mercedes-Benz Trucks','MAN','DAF','Freightliner','Kenworth','Peterbilt','International','IKA','Siam','Dinarg','Autoar','Rastrojero','Dacia','Lada','Tata','Mahindra','Proton','Perodua','McLaren','Koenigsegg','Bugatti','Pagani','Tesla','Rivian','Lucid','NIO','XPeng','Li Auto','Fisker','MINI','Smart','Maybach','DS','Genesis','Alpine') ) NOT NULL, "year" integer NOT NULL, "jobs" text, "kilometers" integer NOT NULL, "kmHistory" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "ownerId" varchar, "spareParts" text, CONSTRAINT "UQ_376f481e04705afcf4a2bc0aa9b" UNIQUE ("licensePlate"), CONSTRAINT "FK_cce467b67e5d4a0012473f985ea" FOREIGN KEY ("ownerId") REFERENCES "client" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_car"("id", "licensePlate", "model", "brand", "year", "jobs", "kilometers", "kmHistory", "createdAt", "updatedAt", "ownerId") SELECT "id", "licensePlate", "model", "brand", "year", "jobs", "kilometers", "kmHistory", "createdAt", "updatedAt", "ownerId" FROM "car"`);
        await queryRunner.query(`DROP TABLE "car"`);
        await queryRunner.query(`ALTER TABLE "temporary_car" RENAME TO "car"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "car" RENAME TO "temporary_car"`);
        await queryRunner.query(`CREATE TABLE "car" ("id" varchar PRIMARY KEY NOT NULL, "licensePlate" varchar(7) NOT NULL, "model" varchar NOT NULL, "brand" varchar CHECK( "brand" IN ('Toyota','Ford','Chevrolet','Volkswagen','Renault','Peugeot','Fiat','Honda','Nissan','Hyundai','Kia','Jeep','Ram','Citroën','Mercedes-Benz','BMW','Audi','Porsche','Ferrari','Lamborghini','Maserati','Bentley','Rolls-Royce','Aston Martin','Jaguar','Land Rover','Volvo','Lexus','Infiniti','Acura','Cadillac','Lincoln','Mazda','Mitsubishi','Suzuki','Subaru','Isuzu','SsangYong','Chery','JAC','Geely','Great Wall','Haval','Lifan','Dongfeng','Foton','JMC','Changan','BYD','MG','Alfa Romeo','Lancia','Seat','Skoda','Opel','Saab','Saturn','Pontiac','Oldsmobile','Mercury','Plymouth','Dodge','Chrysler','Hummer','Daewoo','Daihatsu','Iveco','Scania','Volvo Trucks','Mercedes-Benz Trucks','MAN','DAF','Freightliner','Kenworth','Peterbilt','International','IKA','Siam','Dinarg','Autoar','Rastrojero','Dacia','Lada','Tata','Mahindra','Proton','Perodua','McLaren','Koenigsegg','Bugatti','Pagani','Tesla','Rivian','Lucid','NIO','XPeng','Li Auto','Fisker','MINI','Smart','Maybach','DS','Genesis','Alpine') ) NOT NULL, "year" integer NOT NULL, "jobs" text, "kilometers" integer NOT NULL, "kmHistory" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "ownerId" varchar, CONSTRAINT "UQ_376f481e04705afcf4a2bc0aa9b" UNIQUE ("licensePlate"), CONSTRAINT "FK_cce467b67e5d4a0012473f985ea" FOREIGN KEY ("ownerId") REFERENCES "client" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "car"("id", "licensePlate", "model", "brand", "year", "jobs", "kilometers", "kmHistory", "createdAt", "updatedAt", "ownerId") SELECT "id", "licensePlate", "model", "brand", "year", "jobs", "kilometers", "kmHistory", "createdAt", "updatedAt", "ownerId" FROM "temporary_car"`);
        await queryRunner.query(`DROP TABLE "temporary_car"`);
    }

}
